### PR TITLE
Search form category custom fields issue

### PR DESCRIPTION
**Pull request by vairafiq**
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Security fix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Description
How to reproduce the issue or how to test the changes

1. From the builder assign 2 custom fields in a category
2. Use these 2 fields in search form
3. Try selecting a category in search form

## Any linked issues
Fixes #

## Checklist

- [ ] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

### CODE REVIEW

**Comment by vairafiq** [comment]
If someone comes to result page with a category query then the custom field is not appearing on the form 
image

**Comment by obiPlabon** [comment]
Ajax issue on search home page (use Query Monitor):
image

I have assigned the fields in the Basic section but the fields have been rendered in another section (on both search home and result pages):
image
image

On search result page the fields are not filled with the searched values:
image

**Comment by obiPlabon** [comment]
Builder
- Assigned 2 custom fields in Cat 1.

Search Home
- Cat 1 is selected and those 2 fields appeared.
- Some dummy values were added and clicked on the search button.

Search Result
- Cat 1 is selected
- Those 2 fields didn't appear anywhere!

**Review by obiPlabon — CHANGES_REQUESTED** [review]
check message

**Pull request closed without merging**
