### PR TITLE
Custom Single Listing page improved

### PR DESCRIPTION
**Pull request by kowsar89**
Also fixes Divi page builder issue: https://lobby.sovware.com/wp-admin/admin.php?page=pm_projects#/projects/8/task-lists/110/tasks/1662

### CODE REVIEW

**Comment by vairafiq** [comment]
Please fix the conflict

**Comment by kowsar89** [comment]
updated

**Comment by vairafiq** [comment]
Please fix the conflict and make sure it is still valid with latest changes

**Comment by kowsar89** [comment]
#1187

**Pull request closed without merging**
