### PR TITLE
Prefix added on Add Listing & Registration Page Checkbox (Privacy Policy & Terms Condition) ID

### PR DESCRIPTION
**Pull request by iamibrahimriaz**
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Security fix
- [ ] Improvement
- [ ] New Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Text changes
- [ ] Other... Please describe:

## Description
How to reproduce the issue or how to test the changes

1. Enable Guest Listing
2. Add Listing Submission
3. Registration

image

image

## Checklist

- [x] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

### CODE REVIEW

**Review by vairafiq — CHANGES_REQUESTED** [review]
Please change the template version to 7.8.0

**Comment by vairafiq** [comment]
image
Need to fix this error and update the template version to 7.9.1

**Comment by iamibrahimriaz** [comment]
> image Need to fix this error and update the template version to 7.9.1

**Fixed**

**Review by vairafiq — APPROVED** [review]
Looks good

**Pull request merged**
