### PR TITLE
fixed security issue of system-status

### PR DESCRIPTION
**Pull request by Armanul46**

### CODE REVIEW

**Review by kowsar89 — CHANGES_REQUESTED** [review]
```

FILE: media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/system-status/send-mail.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 11 ERRORS AFFECTING 7 LINES
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 12 | ERROR | Processing form data without nonce verification. (WordPress.Security.NonceVerification.Missing)
 12 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash() or similar (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 12 | ERROR | Detected usage of a non-sanitized input variable: $_POST['_nonce'] (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 17 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash() or similar (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 17 | ERROR | Detected usage of a non-sanitized input variable: $_POST['email'] (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 18 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash() or similar (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 19 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash() or similar (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 20 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash() or similar (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 20 | ERROR | Detected usage of a non-sanitized input variable: $_POST['system_info_url'] (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 22 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash() or similar (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 87 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'wp_create_nonce'.
    |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/system-status/custom-url.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 10 ERRORS AFFECTING 5 LINES
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 14 | ERROR | Processing form data without nonce verification. (WordPress.Security.NonceVerification.Missing)
 14 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash() or similar (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 14 | ERROR | Detected usage of a non-sanitized input variable: $_POST['_nonce'] (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 31 | ERROR | Processing form data without nonce verification. (WordPress.Security.NonceVerification.Missing)
 31 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash() or similar (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 31 | ERROR | Detected usage of a non-sanitized input variable: $_POST['_nonce'] (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 45 | ERROR | $_GET data not unslashed before sanitization. Use wp_unslash() or similar (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 45 | ERROR | Detected usage of a non-sanitized input variable: $_GET['atbdp-system-info'] (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 97 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'wp_create_nonce'.
    |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 98 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'wp_create_nonce'.
    |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/system-status/system-information/system-information.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 31 | ERROR | Detected usage of a non-sanitized input variable: $_SERVER['HTTP_USER_AGENT']
    |       | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 72 | ERROR | Detected usage of a non-sanitized input variable: $_SERVER['SERVER_SOFTWARE']
    |       | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
-----------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/system-status/system-info.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 31 | ERROR | Detected usage of a non-sanitized input variable: $_SERVER['HTTP_USER_AGENT']
    |       | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 72 | ERROR | Detected usage of a non-sanitized input variable: $_SERVER['SERVER_SOFTWARE']
    |       | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
-----------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/system-status/template.php
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 20 | ERROR | All output should be run through an escaping function (like esc_html_e() or esc_attr_e()), found '_e'.
    |       | (WordPress.Security.EscapeOutput.UnsafePrintingFunction)
 23 | ERROR | All output should be run through an escaping function (like esc_html_e() or esc_attr_e()), found '_e'.
    |       | (WordPress.Security.EscapeOutput.UnsafePrintingFunction)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/system-status/system-info-template.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 12 ERRORS AFFECTING 11 LINES
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  51 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
  51 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
  97 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$value'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 155 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 166 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 241 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$icon'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 345 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 400 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 448 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$plugin_name'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 495 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 547 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$override['file']'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 549 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$override['core_version']'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


FILE: media/k/SSD/htdocs/wptest/wp-content/plugins/directorist/includes/system-status/system-information/system-information-template.php
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
FOUND 10 ERRORS AFFECTING 8 LINES
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 482 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$database['database_size']['data']'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 492 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$database['database_size']['data']'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 501 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$database['database_size']['index']'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 515 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 515 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 528 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 528 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$this'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 634 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 699 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '__'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)
 779 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$override['core_version']'.
     |       | (WordPress.Security.EscapeOutput.OutputNotEscaped)

```

**Review by vairafiq — CHANGES_REQUESTED** [review]
FILE: includes/system-status/send-mail.php
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 1 LINE
--------------------------------------------------------------------------------
 12 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash()
    |       | or similar
    |       | (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 12 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST['_nonce']
    |       | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
--------------------------------------------------------------------------------


FILE: includes/system-status/custom-url.php
--------------------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 3 LINES
--------------------------------------------------------------------------------
 14 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash()
    |       | or similar
    |       | (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 14 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST['_nonce']
    |       | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 30 | ERROR | $_POST data not unslashed before sanitization. Use wp_unslash()
    |       | or similar
    |       | (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 30 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_POST['_nonce']
    |       | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
 43 | ERROR | $_GET data not unslashed before sanitization. Use wp_unslash() or
    |       | similar
    |       | (WordPress.Security.ValidatedSanitizedInput.MissingUnslash)
 43 | ERROR | Detected usage of a non-sanitized input variable:
    |       | $_GET['atbdp-system-info']
    |       | (WordPress.Security.ValidatedSanitizedInput.InputNotSanitized)
--------------------------------------------------------------------------------

Time: 263ms; Memory: 4MB

**Review by vairafiq — APPROVED** [review]
phpcs ok and no issue found in application

**Review by kowsar89 — COMMENTED** [review]
phpcs ok, but there are non-security related changes in this commit which should be checked

**Review by vairafiq — APPROVED** [review]

**Review by vairafiq — APPROVED** [review]
checked

**Review by kowsar89 — APPROVED** [review]

**Pull request merged**
