### PR TITLE
Gutenberg blocks with assets fix

### PR DESCRIPTION
**Pull request by obiPlabon**

### CODE REVIEW

**Review by vairafiq — APPROVED** [review]
Looks good from my side

**Review by kowsar89 — CHANGES_REQUESTED** [review]
https://prnt.sc/15kbzdu

**Review by kowsar89 — CHANGES_REQUESTED** [review]
https://prnt.sc/15kwilv

**Review by kowsar89 — APPROVED** [review]
Looks good

**Pull request merged**
