### PR TITLE
Fixed admin only fields data overriding

### PR DESCRIPTION
**Pull request by obiPlabon**
## PR Type
What kind of change does this PR introduce?
- Bugfix
- Security fix
- Improvement
- Refactoring (no functional changes, no API changes)

## Description
Refactored and fixed the following admin-only field override issue:
- Category
- Location
- Tags
- Social media
- Checkbox

## Checklist

- [ ] My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

### CODE REVIEW

**Comment by Armanul46** [comment]
Description overwritten after editing a listing from the frontend

https://prnt.sc/KTccsVRVZwCU

**Comment by Armanul46** [comment]
Works fine

**Comment by vairafiq** [comment]
Issue exists https://www.loom.com/share/2613946dfe4046e899cfc4aa35e115ee

**Review by vairafiq — APPROVED** [review]
Looks good

**Pull request merged**
