### PR TITLE
Fix/theme update

### PR DESCRIPTION
**Pull request by vairafiq**
Issues: https://app.clickup.com/t/1x0gzu7

### CODE REVIEW

**Review by kowsar89 — CHANGES_REQUESTED** [review]
not working

**Review by kowsar89 — CHANGES_REQUESTED** [review]
Doesn't work for onelisting(free) and drealestate theme

**Comment by vairafiq** [comment]
Fixed, Remote API updated

**Review by kowsar89 — APPROVED** [review]
Works now

**Pull request merged**
