### PR TITLE
Refactored add listings

### PR DESCRIPTION
**Pull request by obiPlabon**
## PR Type
What kind of change does this PR introduce?

- Improvement
- Refactoring (no functional changes, no API changes)
- Build related changes
- Text changes

## Description
We need a way to validate and sanitize each field properly to adopt the upcoming changes hence the refactoring. Please be sure to check the following areas carefully-
1. Guest submission
2. All fields validation
3. Error messages due to invalid data
4. Monetization
5. Expiration, featured and others
6. All the other settings related to listings

## Checklist

- My code follows the [WordPress coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)

### CODE REVIEW

**Comment by Armanul46** [comment]
When adding a listing without social information or the video field (although social information and the video are not required), it always gives this notice along with 4 PHP errors.
https://prnt.sc/ghH8xCqTfMPg

**Comment by Armanul46** [comment]
Adding a listing does not work when a required field is assigned as 'Administrative Only'
https://prnt.sc/ebii8bvCOvUB

**Comment by Armanul46** [comment]
The required custom field is not functioning properly when it is assigned under the category.
https://prnt.sc/fZ2a1M27geQY

**Comment by Armanul46** [comment]
Category and location are not saving with the subscriber role

**Comment by Armanul46** [comment]
Works Fine

**Comment by vairafiq** [comment]
After submitting the add listing form, it goes to the 404 page (with and without extension)

image

**Review by vairafiq — APPROVED** [review]
Great work!

**Pull request merged**
