### PR TITLE
fix dashboard nav active item issue

### PR DESCRIPTION
**Pull request by devShamim**
## PR Type
What kind of change does this PR introduce?

- [x] Improvement

## Description
How to reproduce the issue or how to test the changes

1. Install and activate dadvertizing plugin
2. Go to Dashboard page
3. Click on side nav

### CODE REVIEW

**Comment by kowsar89** [comment]
Unable to reproduce, screencast may help

**Comment by devShamim** [comment]
@HeyMehedi

**Comment by devShamim** [comment]
> There is a slight jump: https://www.loom.com/share/5d54dacb9c0c4945a4135fbd0e7424c4

@HeyMehedi we need to use ajax here to prevent jump

**Review by kowsar89 — APPROVED** [review]
Since part of it is fixed, I'm approving this. Need to improve later

**Comment by HeyMehedi** [comment]
> There is a slight jump: https://www.loom.com/share/5d54dacb9c0c4945a4135fbd0e7424c4

It's actually not a directorist issue, it's coming from that custom plugin so that you can leave it.

**Pull request merged**
