### PR TITLE
Update: Deprecated Elementor Method & Add: Search Form Pricing Label

### PR DESCRIPTION
**Pull request by HeyMehedi**
https://developers.elementor.com/v3-0-planned-deprecations/?__cf_chl_captcha_tk__=pmd_70e216d09d286cb01bbd95e6c2de8c5d0c7815b1-1627364122-0-gqNtZGzNAw2jcnBszQvi

### CODE REVIEW

**Comment by obiPlabon** [comment]
@HeyMehedi Bhai, Thank you for the PR. I have some quesitons -

1. What will happen if the user doesn't use elementor version 3.0+ or use any version prior to 3.0? And how are we handling that?
2. Why is there an extra field in the directory builder when the pull request says "Update: Deprecated Elementor Method"?
image

**Comment by HeyMehedi** [comment]
@obiPlabon  Bhai, sure let me explain.
1. When I use any "Direcotirist: Elementor Widget" and the Debug Bar plugin installed, the Debug Bar displaying this deprecated notice: https://i.imgur.com/16kUFkT.png
2. The Pricing Label was missing on Search Form, that's why I add the field.  and yes it was a wrong title, Let me edit now.

Thank you :)

**Review by vairafiq — COMMENTED** [review]
need separate pull for every fix

The pricing label is not in use by default. If it is required in any case please extend it by filter hook. Thanks

**Comment by HeyMehedi** [comment]
Sure, I will.
Thanks

**Pull request closed without merging**
