### PR TITLE
Added: Option to allow users to apply map's default location on listings map view

### PR DESCRIPTION
**Pull request by shamimsaj**

### CODE REVIEW

**Comment by shamimsaj** [comment]
https://wordpress.org/support/topic/default-map-location-not-working-2/

**Review by kowsar89 — CHANGES_REQUESTED** [review]
pls fix markup issue http://prntscr.com/21y1zko

**Review by vairafiq — APPROVED** [review]
tested

**Review by kowsar89 — APPROVED** [review]
pass. @HeyMehedi pls confirm

**Review by vairafiq — APPROVED** [review]
reviewed

**Pull request merged**
