### PR TITLE
Fix/shortcode field issue

### PR DESCRIPTION
**Pull request by syedgalib**

### CODE REVIEW

**Review by vairafiq — CHANGES_REQUESTED** [review]
Requested for more adjustment

**Comment by obiPlabon** [comment]
Screenshot 2021-07-08 at 1 14 47 PM

The scroll area is visible, need to fix css.

**Comment by syedgalib** [comment]
> Screenshot 2021-07-08 at 1 14 47 PM
> 
> The scroll area is visible, need to fix css.

image

Doesn't exists on my end

**Review by vairafiq — APPROVED** [review]
Fixed the issue 
image

@obiPlabon please check on dev mode

**Comment by vairafiq** [comment]
Need a hints or description

**Review by obiPlabon — APPROVED** [review]

**Comment by obiPlabon** [comment]
Screenshot 2021-07-11 at 10 46 33 AM

Approved, though the scrolling issue still exists! "Doesn't exist on my end" doesn't sound a valid reason.

**Pull request merged**
