### PR TITLE
Fixing archive page map issue

### PR DESCRIPTION
**Pull request by syedgalib**

### CODE REVIEW

**Comment by vairafiq** [comment]
Still some errors from JSON (removing from content target='_blank' fix the issue in my case)

**Comment by vairafiq** [comment]
Secure to pass soft data from server and ignore html

**Review by kowsar89 — COMMENTED** [review]
Need action regarding this, either fix the issues and approve or close the pull request

**Comment by vairafiq** [comment]
Please confirm the issue @sovware13

**Pull request closed without merging**
