### PR TITLE
Fixing location map api field

### PR DESCRIPTION
**Pull request by syedgalib**

### CODE REVIEW

**Comment by vairafiq** [comment]
Mybe it has some issue as I have tested it in user site.

**Review by kowsar89 — CHANGES_REQUESTED** [review]
JS error: http://prntscr.com/11dhfht

**Review by kowsar89 — CHANGES_REQUESTED** [review]
Style seems broken

**Review by kowsar89 — CHANGES_REQUESTED** [review]
http://prntscr.com/11oyo7j

**Review by kowsar89 — APPROVED** [review]
Looks good to me

**Pull request merged**
