### PR TITLE
Improving builder data saving flow

### PR DESCRIPTION
**Pull request by syedgalib**

### CODE REVIEW

**Review by kowsar89 — APPROVED** [review]
Seems ok

**Review by vairafiq — COMMENTED** [review]
1. Image not found https://prnt.sc/16ahdiq
2. Settings not saving even changed https://prnt.sc/16ahwvb

**Review by vairafiq — CHANGES_REQUESTED** [review]
Need to check the mentioned issues

**Review by vairafiq — APPROVED** [review]
Now it's OK

**Pull request merged**
