### PR TITLE
Fixed: overlaped advanced filter height issue

### PR DESCRIPTION
**Pull request by shamimsaj**
image

### CODE REVIEW

**Comment by kowsar89** [comment]
@HeyMehedi pls check

**Comment by HeyMehedi** [comment]
checked, @shamimsaj please fix the issue as we discussed.

**Review by kowsar89 — APPROVED** [review]
pass. @HeyMehedi pls confirm

**Comment by HeyMehedi** [comment]
looks good now.

**Review by vairafiq — APPROVED** [review]
pass

**Pull request merged**
