### PR TITLE
Refactored: directory type slug edit option

### PR DESCRIPTION
**Pull request by shamimsaj**
image

### CODE REVIEW

**Review by vairafiq — CHANGES_REQUESTED** [review]
image
Screen: MacBook Pro 14"

**Comment by vairafiq** [comment]
image

**Review by obiPlabon — CHANGES_REQUESTED** [review]
https://www.awesomescreenshot.com/video/6292756?key=25dd52f1768b5ea01f72a5e70c072b26

**Review by obiPlabon — APPROVED** [review]
Looks good.

**Review by vairafiq — APPROVED** [review]

**Pull request merged**
